#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int allisvarybad = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int LoginEdit = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int LoginText = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int NameText = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int PasswordEdit = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int PasswordText = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int RememberMeCheck = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int SignUpbutton = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int btnEnter = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int btnRegister = 2131034120;
			
			// aapt resource value: 0x7f05001e
			public const int button1 = 2131034142;
			
			// aapt resource value: 0x7f05000c
			public const int imageView1 = 2131034124;
			
			// aapt resource value: 0x7f050018
			public const int imageView10 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int imageView11 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int imageView12 = 2131034138;
			
			// aapt resource value: 0x7f05000d
			public const int imageView2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int imageView3 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int imageView4 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int imageView5 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int imageView6 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int imageView7 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int imageView8 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int imageView9 = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int nameEdit = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int tableLayout1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int tableRow1 = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int tableRow2 = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int tableRow3 = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int tableRow4 = 2131034135;
			
			// aapt resource value: 0x7f05001b
			public const int tableRow5 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int textView4 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int textView5 = 2131034141;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
